# Generated by Django 4.2.6 on 2023-11-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_payment_offer_milestone_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_milestone',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer_milestone',
            name='payment_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
