# Generated by Django 4.2.6 on 2023-11-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='color',
            field=models.CharField(choices=[('Brown', 'Brown'), ('Blue', 'Blue'), ('Gray', 'Gray'), ('Green', 'Green'), ('Purple', 'Purple'), ('Yellow', 'Yellow')], default='Gray', max_length=7),
        ),
    ]
