# Generated by Django 4.2.6 on 2023-11-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userprofile_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
