# Generated by Django 3.0.5 on 2023-07-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmessage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='file',
        ),
    ]
