# Generated by Django 4.2.2 on 2023-07-07 13:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('development_category', models.CharField(choices=[('Full stack', 'Full stack'), ('Front-end', 'Front-end'), ('Back-end', 'Back-end')], default='Full stack', max_length=12)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MaxValueValidator(9999999.99), django.core.validators.DecimalValidator(decimal_places=2, max_digits=10)])),
                ('attached_files', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
