# Generated by Django 4.2.6 on 2023-10-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('development_category', models.CharField(choices=[('Full stack', 'Full stack'), ('Front-end', 'Front-end'), ('Back-end', 'Back-end')], default='Full stack', max_length=12)),
                ('budget', models.IntegerField()),
                ('attached_files', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
